{
    
    item_name: '',
    item_desc: '',
    cat_name: '',
    price: 0,
    stock_qty: 0,
    generic_name: [''],
    images: [{ img: '' }],
    inventory: [
      {
        discount: 0,
        item_variation_option_id: 0,
        variation_option_id: 0,
        price: 0,
        regular_price: 0,
        variation_option_name: '',
        qty_in_pcs: 0,
        stock_qty: 0,
        capacity: '',
      },
    ],
    manufacturers: '',
    manufacturers_alias: '',
    sku_type: '',
    item_type: 'medicine',
    is_featured: false,
    comes_under: 'otc',
    is_prescription_required: 0,
    alias: '',
    generic_alias: '',
    is_available: true,
    alternative_items: [],
    related_items: [],
    available_stock_qty_in_pc: 0,
  
}