import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { Providers } from "./providers/providers";

const poppins = Poppins({ subsets: ["latin"], weight: "200" });

export const metadata: Metadata = {
  title: "Pharmasuite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <div className="max-w-7xl mx-auto">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
